# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUsers',
            fields=[
                ('UID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('severity', models.CharField(max_length=10)),
                ('acked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.AppUsers')),
                ('user_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='acked_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.AppUsers'),
        ),
    ]
