# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appusers',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='appusers',
            name='cookie',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='appusers',
            name='password_hash',
            field=models.CharField(max_length=32),
        ),
    ]
