# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160108_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='cookie',
            field=models.CharField(blank=True, default=None, max_length=25),
        ),
    ]
